Fix for #21693 - Rename install directory to 'glassfish5'
javaee/glassfish pull request #21739
Opened 2017-05-05 05:26 UTC by arindam-bandyopadhyay

Fix  #21693 - Rename install directory to 'glassfish5'

2017-05-05 21:48 UTC, arindam-bandyopadhyay commented
@glassfishrobot Run CI tests please

2017-05-08 15:08 UTC, yaminikb requested changes
Couple of comments:
1. You have missed changing the top-level README.md file.
2. I also found following files which have references to glassfish3, I think we should fix them as well:
./main/appserver/extras/embedded/glassfish-uber/build.xml
./main/appserver/tests/appserv-tests/config/emma.xml
./main/appserver/tests/appserv-tests/devtests/cdi/README_Embedded.txt
./main/appserver/tests/appserv-tests/devtests/cdi/smoke-tests/optional-unbundled-beans/foo.txt
./main/appserver/tests/appserv-tests/devtests/ejb/README
./main/appserver/tests/appserv-tests/devtests/transaction/ee/dblogs/base/readme
./main/appserver/tests/appserv-tests/devtests/transaction/ee/hudson_3.x.sh
./main/appserver/tests/appserv-tests/devtests/web/ha/cluster-tests/simple-failover-modified-attribute/src/main/java/com/acme/HttpClient.java
./main/appserver/tests/appserv-tests/devtests/web/ha/cluster-tests/simple-failover-modified-session/src/main/java/com/acme/HttpClient.java
./main/appserver/tests/appserv-tests/devtests/web/hudson-base.sh
./main/appserver/tests/appserv-tests/devtests/web/README_Embedded.txt
./main/appserver/tests/sse/basic/pom.xml
./main/appserver/tests/sse/videoplayer/pom.xml
./main/appserver/tests/sse/videoplayer/README.txt
./main/nucleus/core/logging/src/test/resources/com/sun/enterprise/server/logging/parser/uniform-server.log
./v2/appserv-tests/config/emma.xml
./v2/appserv-tests/devtests/hk2/README
./v2/appserv-tests/devtests/jdbc/connection-pool-perf/sample-console.log
./v2/appserv-tests/devtests/jms/README

Note we could leave out the v2/appserv-tests files.

3. One more file which needs changes is main/appserver/distributions/distributions.xml line #51

2017-05-08 15:08 UTC, yaminikb commented on main/appserver/packager/appserver-base/src/main/docs/README.txt
> -Thank you for downloading GlassFish Server Open Source Edition 4.1!
Some of the other references to 4.1 in the same file which can be changed to 5.0

2017-05-08 16:40 UTC, romain-grecourt commented
Make sure to squash when you accept the pull request.

2017-05-08 17:17 UTC, arindam-bandyopadhyay commented on main/appserver/packager/appserver-base/src/main/docs/README.txt
> -Thank you for downloading GlassFish Server Open Source Edition 4.1!
This file has some more reference to 4.1. However those are mostly related to release notes . So I am not changing them

2017-05-08 17:26 UTC, arindam-bandyopadhyay commented
@glassfishrobot Run CI tests please

2017-05-09 04:07 UTC, yaminikb approved these changes
Changes look good.

2017-05-09 05:27 UTC, merged