Admin GUI dev tests and support for docker tests.
javaee/glassfish pull request #21782
Opened 2017-05-23 07:09 UTC by sumauppa

Introduced docker parameter to run docker tests, when secure admin is already on.
Added few fixes for admin GUI dev tests.

2017-05-23 07:09 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-05-23 11:00 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-05-24 06:25 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-05-24 08:35 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-05-24 10:20 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-05-26 07:06 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-05-26 10:30 UTC, arindam-bandyopadhyay requested changes

2017-05-26 10:30 UTC, arindam-bandyopadhyay commented on main/appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/SpecificTestRule.java
> + * Copyright (c) 2010-2017 Oracle and/or its affiliates. All rights reserved.
Please sync you fork with upstream master , The copyright template is wrong in your fork

2017-05-29 06:54 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-05-29 10:26 UTC, sumauppa commented on main/appserver/admingui/devtests/src/test/java/org/glassfish/admingui/devtests/SpecificTestRule.java
> + * Copyright (c) 2010-2017 Oracle and/or its affiliates. All rights reserved.
Done.

2017-05-29 14:13 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-05-30 04:21 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-05-30 08:57 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-06-06 18:06 UTC, arindam-bandyopadhyay approved these changes

2017-06-06 18:07 UTC, merged