SERVLET4_PUSH_TESTS-21780 #21780
javaee/glassfish pull request #21786
Opened 2017-05-24 21:53 UTC by edburns

Tests for issue #21780 

	modified:   .gitignore
	modified:   main/appserver/tests/appserv-tests/devtests/web/build.xml
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/WebTest.java
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/build.properties
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/build.xml
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/docroot/index.html
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/docroot/my.css
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/servlet/test/FooMethodServlet.java
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/servlet/test/TestServlet.java
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/WebTest.java
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/build.properties
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/build.xml
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/servlet/test/NOTfacesServlet.java
	new file:   main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/servlet/test/TestServlet.java

- Tests from before change to github.

2017-05-24 21:53 UTC, edburns commented
@glassfishrobot Run CI tests please

2017-05-24 21:57 UTC, edburns commented
http://gf-hudson.us.oracle.com/hudson/job/gf-remote-queue/344/

2017-05-24 22:59 UTC, ghost reviewed
Hi Ed, can you comment on the returns?

2017-05-24 22:59 UTC, rlubke commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/WebTest.java
> + * Copyright (c) 2012-2017 Oracle and/or its affiliates. All rights reserved.
This should just be 2017 as it's a new file.

2017-05-24 22:59 UTC, rlubke commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/build.xml
> +    Copyright (c) 1997-2017 Oracle and/or its affiliates. All rights reserved.
The year should just be 2017.

2017-05-24 22:59 UTC, rlubke commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/servlet/test/FooMethodServlet.java
> +                    System.out.println("debug: edburns: sending OK: pathInfo:" + pathInfo);
Probably want to remove this...

2017-05-24 22:59 UTC, rlubke commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/WebTest.java
> + * Copyright (c) 2012-2017 Oracle and/or its affiliates. All rights reserved.
Copyright year.

2017-05-24 22:59 UTC, rlubke commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/build.xml
> +    Copyright (c) 1997-2017 Oracle and/or its affiliates. All rights reserved.
Copyright year.

2017-05-24 22:59 UTC, rlubke commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/servlet/test/FooMethodServlet.java
> +
Shouldn't this return after setting the status?

2017-05-24 22:59 UTC, rlubke commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/servlet/test/FooMethodServlet.java
> +                    res.setStatus(HttpServletResponse.SC_OK);
shouldn't this return after setting the status?

2017-05-24 22:59 UTC, rlubke commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/servlet/test/NOTfacesServlet.java
> +                                    res.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
Shouldn't a return be here after setting the status?

2017-05-24 22:59 UTC, rlubke commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/servlet/test/NOTfacesServlet.java
> +
Missing return?

2017-05-25 18:25 UTC, ghost submitted a review, later dismissed

2017-05-25 18:51 UTC, edburns commented
@glassfishrobot run CI tests please

2017-05-25 19:07 UTC, edburns commented
http://gf-hudson.us.oracle.com/hudson/job/gf-remote-queue/356/

2017-05-26 05:20 UTC, shingwaichan commented
I have the following comments on the change:
1. pushArbitraryMethod/servlet/test/TestServlet.java does not write the body to invoke FOO foo/my.css. 
2. pushArbitraryMethod/WebTest.java has comments and description for "push static file"
3. pushDynamic/WebTest.java has comments and description for "push static file"

It would be good to fix that.

2017-06-05 17:35 UTC, edburns commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/servlet/test/FooMethodServlet.java
> +                    System.out.println("debug: edburns: sending OK: pathInfo:" + pathInfo);
Thanks, removed it.

2017-06-05 17:36 UTC, edburns commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/servlet/test/FooMethodServlet.java
> +                    res.setStatus(HttpServletResponse.SC_OK);
Fixed.

2017-06-05 17:37 UTC, edburns commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushDynamic/servlet/test/NOTfacesServlet.java
> +
Fixed.

2017-06-05 20:03 UTC, shingwaichan requested changes
1. pushArbitraryMethod/WebTest.java, the following description is not correct : 
    stat.addDescription("Unit test for http2 push static file");
2. pushArbitraryMethod/servlet/test/TestServlet.java, we have the following: 
res.getWriter().println("<html><head><title>HTTP2 Test</title><link rel=\"stylesheet\" href=\"/foo/my.css\"></head><body>Hello</body></html>"); 
    The above html body will not access “foo/my.css” through the FOO method.  
    In other words, the pushed “foo/my.css” will not be accessed by a browser.

2017-06-05 21:26 UTC, edburns commented
<img width="594" alt="20170605-glassfish-pr-21786-pusharbitrarymethod" src="https://cloud.githubusercontent.com/assets/75821/26803921/0d91112c-4a14-11e7-8d50-5e4f9c1e9356.png">

This image of chrome net-internals shows the test is effective in the browser as written.

2017-06-05 21:27 UTC, edburns commented
I assert that no further change is needed to the pushArbitraryMethod test and request this review be approved.  

Thanks,

Ed

2017-06-05 23:21 UTC, shingwaichan commented
The chrome net-internals shows the FOO request has arrived. My original change request is that the given http response body "need to" spawn a FOO request. (In other words, the client does not ask for the push promise here.)
Per discussion with Ed, he will update the WebTest.java to verify that the method of push promise is  "FOO" by using client API. And he will investigate the use of javascript to spawn FOO request issue later.

2017-06-06 20:59 UTC, shingwaichan submitted a review, later dismissed

2017-06-06 22:23 UTC, edburns commented
@glassfishrobot run ci tests please

2017-06-07 19:15 UTC, edburns commented
@glassfishrobot run CI tests please

2017-06-07 19:37 UTC, ghost submitted a review, later dismissed

2017-06-07 19:43 UTC, arindam-bandyopadhyay commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/WebTest.java
> + * https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
This is old copyright header.Please update the copyright to the latest copyright header.

2017-06-07 19:43 UTC, arindam-bandyopadhyay commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/build.properties
> +    https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
This is old copyright header.Please update the copyright to the latest copyright header.

2017-06-07 20:01 UTC, shingwaichan commented
To be consistence, we should update main/copyright/src/main/resources/copyright-exclude
 for the copyright rather than adding build.properties in copyright header.
Please see d8c544cfba9bd0dd5fb6b90e5e6943a9bbac3d05 as an example.

2017-06-07 21:23 UTC, shingwaichan approved these changes

2017-06-07 21:24 UTC, edburns commented on main/appserver/tests/appserv-tests/devtests/web/servlet-4.0/pushArbitraryMethod/WebTest.java
> + * https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
I removed the copyright statement and used the copyright-excludes.

2017-06-07 21:24 UTC, edburns commented
@Glassfishrobot run CI tests please

2017-06-08 06:49 UTC, merged