Fix #21738 - Number of Stateful session beans in Passive state is not updated (always 0) in Jconsole
javaee/glassfish pull request #21793
Opened 2017-05-26 06:46 UTC by srinivaskrishnan

Fix for #21738

2017-05-26 06:46 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-05-26 08:01 UTC, yaminikb requested changes
Can you please add a test case?

2017-05-26 08:01 UTC, yaminikb commented on main/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java
> +            _logger.log(Level.WARNING, "Exception in backingStore.size()", e);
Above message doesn't conform to GlassFish logging, should use LogMessageInfo

2017-06-11 04:58 UTC, srinivaskrishnan commented
With previous experience checking in the fix and adding a test case makes the hudson job/CI tests fail. So we need to merge the fix seperately and the test case seperately through different pull request.

2017-06-11 06:07 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-06-16 12:34 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-06-28 03:50 UTC, yaminikb commented
Closing this PR since it is a duplicate.

2017-06-28 03:50 UTC, closed without merging