Fix for #21682 - Connection Pool bug occurs when Connection Validation is enabled and On Any Failure  Close All Connections option is used
javaee/glassfish pull request #21792
Opened 2017-05-26 05:22 UTC by srinivaskrishnan

Fix for #21682

2017-05-26 05:23 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-06-04 17:25 UTC, yaminikb requested changes
Have you run the connectors dev tests?

2017-06-04 17:25 UTC, yaminikb commented on main/appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
> +        // The code below has been commented-out because it is effectively being run AGAIN by the caller
Please remove the commented code.

2017-06-04 17:25 UTC, yaminikb commented on main/appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
> +        // The wrapper method addResource() needs to be called instead of ds.addResource(), so that NumConnFree gets incremented after creating the new resource
Remove commented code

2017-06-05 10:16 UTC, srinivaskrishnan commented on main/appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
> +        // The code below has been commented-out because it is effectively being run AGAIN by the caller
Done

2017-06-05 10:16 UTC, srinivaskrishnan commented on main/appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java
> +        // The wrapper method addResource() needs to be called instead of ds.addResource(), so that NumConnFree gets incremented after creating the new resource
Done

2017-06-09 04:25 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-06-16 12:33 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-06-19 16:42 UTC, yaminikb requested changes
I had given this comment before - please remove commented code. It just clutters and impacts readability  of the code.

2017-06-22 05:56 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-06-22 06:00 UTC, srinivaskrishnan reviewed
Removed the commented code

2017-06-22 07:10 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-06-23 07:16 UTC, closed without merging