Fixes #21843 When asadmin get-client-stubs doesn't find application, …
javaee/glassfish pull request #21855
Opened 2017-06-15 11:00 UTC by mukumawa

…then command should fail

2017-06-15 11:00 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-06-19 06:43 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-06-19 16:12 UTC, yaminikb requested changes
Can you please add a test (under deployment dev tests) for this?

2017-06-28 02:54 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-06-30 05:49 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-04 04:58 UTC, yaminikb commented
@glassfishrobot run ci tests please

2017-07-06 11:21 UTC, yaminikb commented
@glassfishrobot run ci tests please

2017-07-07 08:53 UTC, mukumawa commented
@glassfishrobot run ci tests please

2017-07-13 16:58 UTC, arindam-bandyopadhyay commented
@glassfishrobot run ci tests please

2017-07-14 06:13 UTC, mukumawa commented
@glassfishrobot run ci tests please

2017-07-17 11:36 UTC, mukumawa commented
@glassfishrobot run ci tests please

2017-07-17 13:53 UTC, yaminikb requested changes

2017-07-17 13:53 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/admin/cli/build.xml
> +     <target name="cli-group-4" depends="setup, clientstubs, logging-command,load-balancer, getset, misc-commands, teardown"/>
It can also be added to "cli" target which runs all tests.

2017-07-17 16:13 UTC, mukumawa commented
@glassfishrobot run ci tests please

2017-07-17 16:15 UTC, mukumawa commented on appserver/tests/appserv-tests/devtests/admin/cli/build.xml
> +     <target name="cli-group-4" depends="setup, clientstubs, logging-command,load-balancer, getset, misc-commands, teardown"/>
done

2017-07-17 16:36 UTC, yaminikb approved these changes

2017-07-18 05:11 UTC, merged