Create a new test suite in CI pipeline for admin GUI tests
javaee/glassfish pull request #21886
Opened 2017-06-20 12:40 UTC by kokil12

Fixes #21885 : Adding a script run_test.sh and doing necessary changes to make the admingui devtests run on hudson.

2017-06-21 07:17 UTC, sumauppa commented
@glassfishrobot Run CI tests please

2017-06-21 20:15 UTC, kokil12 commented
@glassfishrobot Run CI tests please

2017-06-29 15:46 UTC, yaminikb requested changes

2017-06-29 15:46 UTC, yaminikb commented on appserver/admingui/devtests/run_test.sh
> +  touch /tmp/password.txt
I see all tests generally create the password file in APS_HOME, lets be consistent.

2017-06-29 15:46 UTC, yaminikb commented on appserver/admingui/devtests/run_test.sh
> +  echo "AS_ADMIN_NEWPASSWORD=admin" >> /tmp/password.txt
We shouldn't hard code passwords, we should generate a random one and use that.

2017-06-29 15:46 UTC, yaminikb commented on appserver/admingui/devtests/run_test.sh
> +  export PATH=$M2_HOME/bin:$JAVA_HOME/bin:$PATH
1. M2_HOME, PATH is already set in common_test.sh, no need to set here.
2. Did you mean to set M2_REPO above? MAVEN_REPO is not used.

2017-06-30 04:45 UTC, sumauppa commented on appserver/admingui/devtests/run_test.sh
> +  echo "AS_ADMIN_NEWPASSWORD=admin" >> /tmp/password.txt
In GUI dev tests if secure admin is on, user name and passwords are hardcoded. We need these values if secure admin is on. That is the reason Kokil added these lines.

2017-07-10 10:23 UTC, yaminikb requested changes

2017-07-10 10:23 UTC, yaminikb commented on appserver/admingui/devtests/run_test.sh
> +# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
Fix the copyright text

2017-07-10 10:30 UTC, kokil12 commented
Fixed the copyright text.

2017-07-11 06:07 UTC, kokil12 commented
@glassfishrobot Run CI tests please

2017-07-11 08:24 UTC, yaminikb approved these changes

2017-07-11 08:25 UTC, merged