weld3 integration code
javaee/glassfish pull request #21895
Opened 2017-06-21 05:09 UTC by ankathur

2017-06-21 05:16 UTC, ankathur commented
@glassfishrobot Run CI tests please

2017-06-21 05:18 UTC, arindam-bandyopadhyay commented on main/appserver/pom.xml
> +    DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
There is no main/ anymore.

2017-06-21 05:18 UTC, arindam-bandyopadhyay commented on main/appserver/web/weld-integration/src/test/java/org/glassfish/weld/services/TransactionServicesImplTest.java
> + *
There is no main/

2017-06-21 05:19 UTC, arindam-bandyopadhyay requested changes
Please remove main/ from the PR

2017-06-21 07:15 UTC, ankathur commented
@glassfishrobot Run CI tests please

2017-06-21 16:14 UTC, yaminikb requested changes
Please fix the license URL in EjbInterceptorTest.java and TransactionServicesImplTest.java

2017-06-22 06:40 UTC, ankathur commented
@glassfishrobot Run CI tests please

2017-06-22 19:36 UTC, ankathur commented
@glassfishrobot Run CI tests please

2017-06-23 03:59 UTC, yaminikb requested changes

2017-06-23 03:59 UTC, yaminikb commented on appserver/deployment/dol/src/test/java/com/sun/enterprise/deployment/EjbInterceptorTest.java
>   * or packager/legal/LICENSE.txt.  See the License for the specific
License text path needs to be fixed.

2017-06-23 06:18 UTC, ankathur commented on appserver/deployment/dol/src/test/java/com/sun/enterprise/deployment/EjbInterceptorTest.java
>   * or packager/legal/LICENSE.txt.  See the License for the specific
Fixed.

2017-06-27 09:23 UTC, merged