Fixes #21916 Handle NULL byte injection
javaee/glassfish pull request #21917
Opened 2017-06-23 07:16 UTC by mukumawa

2017-06-23 07:19 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-06-27 06:33 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-06-27 10:28 UTC, yaminikb submitted a review, later dismissed

2017-06-28 05:27 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-06-30 05:49 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-06-30 14:43 UTC, edburns submitted a review, later dismissed
PartItem.java

Line 739 and 753.  Do we trust that getPath() will never return null?

2017-06-30 15:21 UTC, shingwaichan requested changes
Please use logging message rather hardcode strange in exception message. See the usage in other file, such as ApplicationContext.java

2017-06-30 15:32 UTC, edburns submitted a review, later dismissed
Caveat: I am not familiar with this code.  However, I am able to offer general feedback on these changes.  I suggest you check for a null return from getPath() before dereferencing the returned pointer from that method.

2017-07-03 07:41 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-04 04:52 UTC, yaminikb commented on appserver/web/web-core/src/main/java/org/apache/catalina/fileupload/PartItem.java
> +                if (repository.getPath() == null || repository.getPath().contains("\0")) {
This doesn't seem right. The isDirectory check has succeeded at this point, so getPath() can't be null. You can quickly check by running FindBugs.

2017-07-04 11:03 UTC, mukumawa commented on appserver/web/web-core/src/main/java/org/apache/catalina/fileupload/PartItem.java
> +                if (repository.getPath() == null || repository.getPath().contains("\0")) {
I have checked the findbugs locally. I am got findbug here .

2017-07-05 05:45 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-07 05:26 UTC, shingwaichan commented on appserver/web/web-core/src/main/java/org/apache/catalina/fileupload/PartItem.java
> +                if (repository.getPath() == null || repository.getPath().contains("\0")) {
If the repository.getPath() is really null, then it should not use the REPOSITORY_PATH_CONTAIN_NULL_CHARACTER message.

2017-07-07 11:24 UTC, shingwaichan reviewed
The null check (file != null) for the private method deleteFile seems redundant here. Please double check the usage in PartItem.java.

2017-07-10 16:25 UTC, shingwaichan approved these changes

2017-07-11 05:29 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-11 09:40 UTC, merged

2017-07-11 09:42 UTC, yaminikb commented
Merged after confirming that all tests passed except JDBC which is unrelated to this change.