Fixes #21893 Unable to start cluster if Japanese (or Non-ASCII) characters are ent…
javaee/glassfish pull request #21947
Opened 2017-06-29 10:29 UTC by mukumawa

…ered in description field

2017-06-29 10:30 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-06-29 17:43 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-06-30 05:51 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-04 04:33 UTC, yaminikb requested changes

2017-07-04 04:33 UTC, yaminikb commented on nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXmlPreParser.java
> +            InputStreamReader isr = new InputStreamReader(in, Charset.defaultCharset().toString());
You need to close the stream reader.

2017-07-04 06:39 UTC, mukumawa commented on nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXmlPreParser.java
> +            InputStreamReader isr = new InputStreamReader(in, Charset.defaultCharset().toString());
Done

2017-07-04 06:40 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-04 08:55 UTC, yaminikb requested changes

2017-07-04 08:55 UTC, yaminikb commented on nucleus/admin/config-api/src/main/java/org/glassfish/config/support/DomainXmlPreParser.java
> +            try {
You can instead call cleanup().

2017-07-04 11:36 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-05 04:48 UTC, yaminikb approved these changes

2017-07-05 04:49 UTC, merged