Fixing 21906# Enabling Connector Tests as Part of the RQ Job
javaee/glassfish pull request #21946
Opened 2017-06-29 06:05 UTC by naman223

2017-06-29 06:05 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-06-29 06:28 UTC, yaminikb requested changes

2017-06-29 06:28 UTC, yaminikb commented on appserver/tests/v2-tests/appserv-tests/devtests/connector/run_test.sh
> +# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
2018??

2017-06-29 06:28 UTC, yaminikb commented on appserver/tests/v2-tests/appserv-tests/devtests/connector/SunRaXml/cci-embedded/build.xml
> +                <!--antcall target="reconfig-common"/-->
Please delete this call (here and in all occurrences below) instead of commenting

2017-06-29 09:51 UTC, naman223 commented on appserver/tests/v2-tests/appserv-tests/devtests/connector/run_test.sh
> +# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
Copy/Paste error. Fixed.

2017-06-29 09:51 UTC, naman223 commented on appserver/tests/v2-tests/appserv-tests/devtests/connector/SunRaXml/cci-embedded/build.xml
> +                <!--antcall target="reconfig-common"/-->
All Fixed.

2017-06-29 09:51 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-06-29 15:03 UTC, yaminikb approved these changes

2017-06-30 04:58 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-06-30 12:46 UTC, merged