weld3 integration code (#21895)
javaee/glassfish pull request #21950
Opened 2017-06-29 16:42 UTC by ankathur

Weld 3 Integration

2017-06-29 16:43 UTC, ankathur commented
@glassfishrobot Run CI tests please

2017-06-30 03:17 UTC, yaminikb requested changes

2017-06-30 03:17 UTC, yaminikb commented on appserver/deployment/dol/src/test/java/com/sun/enterprise/deployment/EjbInterceptorTest.java
> + * or packager/legal/LICENSE.txt.  See the License for the specific
license text file path should be fixed.

2017-06-30 03:17 UTC, yaminikb commented on appserver/web/weld-integration/src/test/java/org/glassfish/weld/services/TransactionServicesImplTest.java
> + * or packager/legal/LICENSE.txt.  See the License for the specific
Fix license text file path

2017-07-03 05:56 UTC, yaminikb approved these changes

2017-07-03 06:00 UTC, merged

2017-07-03 06:12 UTC, yaminikb commented
Just a point on the CI tests failed message, all the tests actually passed except for the copyright tests. The copyright issues were fixed and verified separately by running just that test alone. Hence, merged the PR.