Fixing 21965 # Reporting for Deployment Tests.
javaee/glassfish pull request #21966
Opened 2017-07-03 07:50 UTC by naman223

In the following tests - deployment_all, deployment_cluster_all, at least some failures are not reported in the junit report file.

2017-07-03 07:50 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-07-03 11:31 UTC, arindam-bandyopadhyay commented on appserver/tests/appserv-tests/devtests/deployment/run_test.sh
> +  deployment_all )
Why we need to explicitly define deployment_all target. Isn't it taken care by run_test_id

2017-07-03 11:33 UTC, arindam-bandyopadhyay requested changes
I don't think we need to explicitly add deployment_all target in the deployment run_test.sh

2017-07-04 05:16 UTC, naman223 commented on appserver/tests/appserv-tests/devtests/deployment/run_test.sh
> +  deployment_all )
I added for easy to run the tests locally. 
No, run_test_id is doing some intialization which I don't want locally so just added target, I set S1AS & APS, it works fine so added.

2017-07-04 09:40 UTC, arindam-bandyopadhyay approved these changes

2017-07-04 09:48 UTC, merged