Fix #21974 Add Yasson basic test
javaee/glassfish pull request #21975
Opened 2017-07-04 09:54 UTC by Verdent

2017-07-04 09:55 UTC, Verdent commented
@glassfishrobot Run CI tests please

2017-07-04 15:42 UTC, yaminikb requested changes

2017-07-04 15:42 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/web/yasson/YassonTest.java
> + * Copyright (c) 2011-2017 Oracle and/or its affiliates. All rights reserved.
Copyright year needs to be fixed in all the new files.

2017-07-04 15:42 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/web/yasson/YassonTest.java
> +    private static final String TEST_NAME = "trasnform-to-json-by-yasson";
Typo

2017-07-04 15:42 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/web/yasson/build.xml
> +    <target name="enable-access-logging" depends="init-common">
Just curious, is access logging for debugging purpose?

2017-07-10 08:25 UTC, Verdent commented
Thank you @yaminikb for suggestions. I have implemented them in new commit.

2017-07-10 08:25 UTC, Verdent commented
@glassfishrobot Run CI tests please

2017-07-10 10:56 UTC, yaminikb approved these changes

2017-07-11 04:15 UTC, yaminikb commented
@Verdent Can you please sync your branch and re-run the tests?

2017-07-11 20:41 UTC, arindam-bandyopadhyay commented
@glassfishrobot Run CI tests please

2017-07-12 03:37 UTC, merged