Fix for #21909: Error message 'Flashlight listener registration failed  for listener class'  is found in server.log when EJB monitoring is HIGH
javaee/glassfish pull request #22004
Opened 2017-07-07 11:08 UTC by srinivaskrishnan

Fix for #21909: Error message 'Flashlight listener registration failed  for listener class'  is found in server.log when EJB monitoring is HIGH

2017-07-11 06:29 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-07-11 09:25 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-07-13 13:27 UTC, yaminikb requested changes

2017-07-13 13:27 UTC, yaminikb commented on appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/BaseContainer.java
> +    boolean isMonitorRegistryMediatorCreated = false;
Fix format

2017-07-13 13:27 UTC, yaminikb commented on appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java
> +        _logger.log(Level.FINE, "[SFSBContainer] registered monitorable");
Add isLoggable check

2017-07-13 16:54 UTC, srinivaskrishnan commented
@glassfishrobot Run CI tests please

2017-07-14 04:41 UTC, yaminikb approved these changes

2017-07-14 04:42 UTC, merged