Fixes 22034: No check for duplicate @ManagedBean names
javaee/glassfish pull request #22035
Opened 2017-07-13 06:16 UTC by rahul-rs-srivastava

Fixes #22034

2017-07-13 06:19 UTC, rahul-rs-srivastava commented
@glassfishrobot Run CI tests please

2017-07-13 10:05 UTC, mskdeepak-oracle reviewed
Looks Good. 
You might want to add a devtest - A negative test  checking that deployment fails in case a duplicate Managed Bean is present.

2017-07-13 17:10 UTC, yaminikb requested changes

2017-07-13 17:10 UTC, yaminikb commented on appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/BundleDescriptor.java
> +                        String msg = String.format("Error processing ManagedBean \"%s\" with Name \"%s\", "
Message should come from a resource bundle instead of being hard coded.

2017-07-14 11:46 UTC, rahul-rs-srivastava commented on appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/BundleDescriptor.java
> +                        String msg = String.format("Error processing ManagedBean \"%s\" with Name \"%s\", "
Added message to resource bundle

2017-07-14 11:48 UTC, rahul-rs-srivastava reviewed
Fixed

2017-07-14 11:49 UTC, rahul-rs-srivastava commented
@glassfishrobot Run CI tests please

2017-07-17 06:57 UTC, rahul-rs-srivastava commented
@glassfishrobot Run CI tests please

2017-07-17 08:22 UTC, yaminikb approved these changes

2017-07-17 09:17 UTC, merged