Create a new test suite in CI pipeline for persistence tests
javaee/glassfish pull request #22059
Opened 2017-07-17 11:07 UTC by kokil12

Fixes #22058 : Adding run_test.sh script to make the "persistence_all" test suite run on hudson.

2017-07-17 12:11 UTC, kokil12 commented
@glassfishrobot Run CI tests Please

2017-07-19 09:23 UTC, kokil12 commented
@glassfishrobot Run CI tests Please

2017-07-20 06:03 UTC, yaminikb requested changes

2017-07-20 06:03 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/persistence/tests/packaging/resultCount.sh
> +echo "************************">>$APS_HOME/devtests/cmp/count.txt;
Fix the count.txt path in all lines, it is incorrectly pointing to "cmp"

2017-07-20 06:24 UTC, yaminikb submitted a review, later dismissed

2017-07-20 07:19 UTC, arindam-bandyopadhyay requested changes

2017-07-20 07:19 UTC, arindam-bandyopadhyay commented on appserver/tests/appserv-tests/devtests/persistence/run_test.sh
> +  unzip_test_resources $WORKSPACE/bundles/glassfish.zip
Please add the cleanup logic. Please refer https://github.com/javaee/glassfish/blob/master/appserver/tests/appserv-tests/devtests/admin/cli/run_test.sh#L72

2017-07-20 20:01 UTC, arindam-bandyopadhyay commented
Please add the test id in appserver/tests/test_groups/gating

2017-07-24 14:10 UTC, arindam-bandyopadhyay commented
@glassfishrobot Run CI tests Please

2017-07-24 16:46 UTC, kokil12 commented
@glassfishrobot Run CI tests Please

2017-07-24 18:56 UTC, arindam-bandyopadhyay approved these changes

2017-07-24 18:57 UTC, merged