Providing override for application/json String.
javaee/glassfish pull request #22069
Opened 2017-07-18 15:24 UTC by pavelbucek

This change is effectively disabling JSON-B processing for management app; concretely

http://localhost:4848/management/domain/view-log/details.json

(served by StructuredLogViewerResource).

2017-07-18 15:29 UTC, pavelbucek commented
@glassfishrobot run ci tests please

2017-07-19 04:13 UTC, yaminikb requested changes

2017-07-19 04:13 UTC, yaminikb commented on nucleus/admin/rest/rest-service/src/main/java/org/glassfish/admin/rest/provider/JsonStringReaderWriter.java
> + * http://glassfish.java.net/public/CDDL+GPL_1_1.html
Copyright needs to be fixed. All other CI tests have passed.

2017-07-19 06:27 UTC, pavelbucek commented
@glassfishrobot run ci tests please

2017-07-19 07:45 UTC, yaminikb approved these changes

2017-07-19 11:13 UTC, merged