Fixing #21072, NullPointerException while lazy initialization of connection pools.
javaee/glassfish pull request #22083
Opened 2017-07-20 09:54 UTC by naman223

Fixing #21072 , handling the NPE.

2017-07-20 09:55 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-07-24 09:17 UTC, naman223 commented
CI Test: http://sca00kou.us.oracle.com:8080/job/gf-remote-queue/381/

2017-07-24 11:16 UTC, arindam-bandyopadhyay commented
@glassfishrobot Run CI tests please

2017-07-25 05:46 UTC, arindam-bandyopadhyay commented
@glassfishrobot Run CI tests please

2017-08-03 05:33 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-08-03 06:32 UTC, yaminikb requested changes

2017-08-03 06:32 UTC, yaminikb commented on appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolManagerImpl.java
> +                    _logger.info("Skipping lazy connection disassociation due to Resource Handle: null");
Retrieve messages from resource bundle instead of hard coding.

2017-08-03 17:30 UTC, naman223 commented on appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/PoolManagerImpl.java
> +                    _logger.info("Skipping lazy connection disassociation due to Resource Handle: null");
Fixed the Same.

2017-08-03 17:31 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-08-04 05:26 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-08-07 05:47 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-08-07 08:21 UTC, h2002044 approved these changes

2017-08-07 08:24 UTC, yaminikb approved these changes

2017-08-07 08:25 UTC, merged