Moving connector tests to multiple splits.
javaee/glassfish pull request #22103
Opened 2017-07-25 08:41 UTC by naman223

Fixing #22102 

Splitting them to multiple tests

2017-07-25 08:42 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-07-25 11:19 UTC, arindam-bandyopadhyay requested changes

2017-07-25 11:19 UTC, arindam-bandyopadhyay commented on appserver/tests/appserv-tests/devtests/connector/v3/run_test.sh
>    cd $APS_HOME/../v2-tests/appserv-tests
/v2-tests/appserv-tests folder would be deleted soon. That is the whole purpose of moving test from v2-tests/appserv-tests to appserv-tests . Please remove this reference

2017-07-25 11:19 UTC, arindam-bandyopadhyay commented on appserver/tests/appserv-tests/devtests/connector/v3/run_test.sh
>    cd $APS_HOME/../v2-tests/appserv-tests
/v2-tests/appserv-tests folder would be deleted soon. That is the whole purpose of moving test from v2-tests/appserv-tests to appserv-tests . Please remove this reference

2017-07-31 05:14 UTC, naman223 commented
@glassfishrobot Run CI tests please

2017-07-31 11:18 UTC, arindam-bandyopadhyay commented
@glassfishrobot Run CI tests please

2017-07-31 13:41 UTC, arindam-bandyopadhyay approved these changes

2017-07-31 13:43 UTC, merged