Fixes #22104  Fix Findbugs
javaee/glassfish pull request #22105
Opened 2017-07-25 09:17 UTC by mukumawa

2017-07-25 09:19 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-25 14:48 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-26 06:09 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-26 08:56 UTC, jayasheelankumar commented on appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/AppClientFacade.java
> +/*
Please remove the unused code blocks rather than commenting.

2017-07-26 10:07 UTC, mukumawa commented on appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/AppClientFacade.java
> +/*
done

2017-07-26 10:09 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-27 04:59 UTC, yaminikb requested changes

2017-07-27 04:59 UTC, yaminikb commented on appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/TestMain.java
> +            CommandLaunchInfo info = CommandLaunchInfo.newInstance(agentArgs);
Won't this cause a DLS warning?

2017-07-27 04:59 UTC, yaminikb commented on appserver/batch/glassfish-batch-commands/src/main/java/org/glassfish/batch/ListBatchJobExecutions.java
> +    /*
Remove the commented code

2017-07-27 04:59 UTC, yaminikb commented on appserver/batch/glassfish-batch-connector/src/main/java/org/glassfish/batch/spi/impl/BatchRuntimeHelper.java
> +                                //JobOperator jobOperator = BatchRuntime.getJobOperator();
Remove the line

2017-07-27 08:05 UTC, mukumawa commented
@glassfishrobot Run CI tests please

2017-07-28 04:55 UTC, yaminikb approved these changes

2017-07-28 04:58 UTC, merged