Split servlet tck tests into groups to reduce overall runtime
javaee/glassfish pull request #22118
Opened 2017-07-27 10:44 UTC by debayan-gupta

2017-07-27 10:44 UTC, debayan-gupta commented
@glassfishrobot Run CI tests please

2017-07-27 17:25 UTC, arindam-bandyopadhyay requested changes

2017-07-27 17:25 UTC, arindam-bandyopadhyay commented on appserver/tests/cts_smoke/run_test.sh
> +	elif [[ $1 = "servlet_tck_"* ]]; then
servlet_tck_all would fail in this logic

2017-07-27 17:25 UTC, arindam-bandyopadhyay commented on appserver/tests/cts_smoke/test_dir.properties
> +servlet-api-servlet-http=servlet/api/javax_servlet_http
Please add copyright in the file

2017-07-27 17:25 UTC, arindam-bandyopadhyay commented on appserver/tests/cts_smoke/test_dir.properties
> +servlet-compat=servlet/compat
How does it handle the scenario if a new folder is added? Can one of the test id can cover "all remaning folders"

2017-07-28 06:09 UTC, debayan-gupta commented on appserver/tests/cts_smoke/run_test.sh
> +	elif [[ $1 = "servlet_tck_"* ]]; then
This is already tested against 'all' target and it passed. I am not sure about any other use case where it should fail.

2017-07-28 06:09 UTC, debayan-gupta commented on appserver/tests/cts_smoke/test_dir.properties
> +servlet-api-servlet-http=servlet/api/javax_servlet_http
Added copyright.

2017-07-28 06:22 UTC, debayan-gupta commented on appserver/tests/cts_smoke/test_dir.properties
> +servlet-compat=servlet/compat
As discussed, a logic of failing test run in case some new folder is being added but properties is not updated, should be added.

2017-07-28 17:43 UTC, debayan-gupta commented
Added logic for failing tests if a new test directory added but property file  is not updated.

2017-07-28 17:43 UTC, debayan-gupta commented
@glassfishrobot Run CI tests please

2017-07-31 11:22 UTC, debayan-gupta commented
@glassfishrobot Run CI tests please

2017-07-31 12:05 UTC, arindam-bandyopadhyay approved these changes

2017-07-31 13:44 UTC, merged