Fixes #21306: FileUpload doesn't in webFragment application
javaee/glassfish pull request #22124
Opened 2017-07-28 07:01 UTC by ht26200

@glassfishrobot Run CI tests please

2017-07-28 08:38 UTC, ht26200 commented
@glassfishrobot Run CI tests please

2017-07-28 17:14 UTC, shingwaichan requested changes
We should invoke #scanXmlDefinedClassesIfNecessary instead of having the for loopier jsf.
Also, it would be good to add a test case in appserv-tests/devtests/web

2017-08-04 07:01 UTC, ht26200 commented
@glassfishrobot Run CI tests please

2017-08-04 07:29 UTC, shingwaichan submitted a review, later dismissed

2017-08-04 13:37 UTC, yaminikb requested changes

2017-08-04 13:37 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/web/servlet-3.0/webFragmentWithFileUpload/WebTest.java
> + * Copyright (c) 1997-2017 Oracle and/or its affiliates. All rights reserved.
Year should be just 2017

2017-08-04 13:37 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/web/servlet-3.0/webFragmentWithFileUpload/build.xml
> +    Copyright (c) 1997-2017 Oracle and/or its affiliates. All rights reserved.
Year should be just "2017"

2017-08-04 13:37 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/web/servlet-3.0/webFragmentWithFileUpload/descriptor/web-fragment.xml
> +<web-fragment version="3.0" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/x
Missing copyright

2017-08-04 13:37 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/web/servlet-3.0/webFragmentWithFileUpload/docroot/single.xhtml
> +<?xml version="1.0" encoding="UTF-8"?>
Missing copyright

2017-08-04 13:37 UTC, yaminikb commented on appserver/tests/appserv-tests/devtests/web/servlet-3.0/webFragmentWithFileUpload/servlet/Bean.java
> +package fileupload;
Missing copyright

2017-08-07 04:21 UTC, ht26200 commented
Starting CI tests run

2017-08-07 08:00 UTC, ht26200 commented
@glassfishrobot Run CI tests please

2017-08-08 03:07 UTC, ht26200 commented
@glassfishrobot Run CI tests please

2017-08-08 04:46 UTC, yaminikb approved these changes

2017-08-08 04:47 UTC, merged