Fixing Issue #21718
javaee/glassfish pull request #22121
Opened 2017-07-27 18:51 UTC by ankathur

According to CDI 2.0 spec section 12.1 "Archives with extensions and no beans.xml file are not candidates for implicit bean discovery"

#21718

2017-07-27 18:52 UTC, ankathur commented
@glassfishrobot Run CI Tests please

2017-07-27 19:10 UTC, arindam-bandyopadhyay commented
@ankathur Please consider putting more descriptive title of the PR

2017-07-27 19:16 UTC, jjsnyder submitted a review, later dismissed
Looks good.

2017-07-27 19:44 UTC, arindam-bandyopadhyay requested changes

2017-07-27 19:44 UTC, arindam-bandyopadhyay commented on appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
> +                                }
Consider fixing the formatting

2017-07-28 06:47 UTC, ankathur commented
@glassfishrobot Run CI Tests please

2017-07-30 20:35 UTC, arindam-bandyopadhyay commented on appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
> +
do you really need to change this file ?

2017-07-31 09:56 UTC, ankathur reviewed
removed BeanDeploymentArchiveImpl from PR

2017-07-31 09:56 UTC, ankathur commented on appserver/web/weld-integration/src/main/java/org/glassfish/weld/BeanDeploymentArchiveImpl.java
> +                                }
updated the file.

2017-08-01 18:43 UTC, arindam-bandyopadhyay approved these changes

2017-08-01 18:43 UTC, arindam-bandyopadhyay commented
@glassfishrobot Run CI Tests please

2017-08-02 10:54 UTC, merged