Fixes #22207 :  Prepare all help files/text in admingui for release
javaee/glassfish pull request #22228
Opened 2017-08-21 09:20 UTC by pranjal10

Fixes #22207.

2017-08-21 09:33 UTC, pranjal10 commented
@glassfishrobot Run CI tests please

2017-08-22 11:29 UTC, pranjal10 commented
@glassfishrobot Run CI tests please

2017-08-22 11:44 UTC, pranjal10 commented
@glassfishrobot Run CI tests please

2017-08-22 15:46 UTC, yaminikb requested changes

2017-08-22 15:46 UTC, yaminikb commented on appserver/admingui/jdbc/src/main/help/en/help/docinfo.html
> +<p>Copyright &copy; 2017,&nbsp;Oracle and/or its affiliates. All rights reserved.</p>
Fix year

2017-08-22 15:46 UTC, yaminikb commented on appserver/admingui/jms-plugin/src/main/help/en/help/docinfo.html
> +<p>Copyright &copy; 2017,&nbsp;Oracle and/or its affiliates. All rights reserved.</p>
fix year

2017-08-22 15:46 UTC, yaminikb commented on appserver/admingui/jts/src/main/help/en/help/docinfo.html
> +<p>Copyright &copy; 2017,&nbsp;Oracle and/or its affiliates. All rights reserved.</p>
fix year

2017-08-22 15:46 UTC, yaminikb commented on appserver/admingui/web/src/main/help/en/help/docinfo.html
> +<p>Copyright &copy; 2017,&nbsp;Oracle and/or its affiliates. All rights reserved.</p>
fix year

2017-08-22 15:46 UTC, yaminikb commented on nucleus/pom.xml
>      <dependencies>
Unwanted nucleus pom changes are showing up

2017-08-23 05:57 UTC, pranjal10 commented
@glassfishrobot Run CI tests please

2017-08-23 07:35 UTC, yaminikb approved these changes
Looks fine

2017-08-23 07:37 UTC, merged