Avoid fetching external DTD/ schema
javaee/glassfish pull request #22327
Opened 2017-11-06 06:38 UTC by mskdeepak-oracle

2017-11-06 06:39 UTC, mskdeepak-oracle commented
@glassfishrobot Run CI tests please

2017-11-07 08:22 UTC, mskdeepak-oracle commented
@glassfishrobot Run CI tests please

2017-11-07 13:29 UTC, honghzzhang submitted a review, later dismissed
Changes look ok to me.

2017-11-08 03:48 UTC, yaminikb requested changes

2017-11-08 03:48 UTC, yaminikb commented on appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/AppClientContainerBuilder.java
>  import org.xml.sax.SAXParseException;
This import is unused, can be removed

2017-11-08 03:48 UTC, yaminikb commented on appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/Launchable.java
>  import org.xml.sax.SAXParseException;
Don't you need to replace the exception at line #189?

2017-11-08 03:48 UTC, yaminikb commented on appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/MainClassLaunchable.java
>  import org.xml.sax.SAXParseException;
Unused import can be removed.

2017-11-08 03:48 UTC, yaminikb commented on appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/UndeployedLaunchable.java
>  import org.xml.sax.SAXParseException;
There are still some methods throwing the wrapped exception. Do we need it?

2017-11-08 03:48 UTC, yaminikb commented on appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/archivist/AppClientArchivist.java
>  import org.xml.sax.SAXParseException;
Unused import

2017-11-08 03:48 UTC, yaminikb commented on appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/archivist/ApplicationArchivist.java
>  import org.xml.sax.SAXParseException;
Unused import

2017-11-08 03:48 UTC, yaminikb commented on appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/archivist/ApplicationFactory.java
>  import org.xml.sax.SAXParseException;
Please remove the unused import in all files.

2017-11-08 03:48 UTC, yaminikb commented on appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/LocalStrings.properties
> +invalid.schema=Requested schema not in local repository, check for typos in the descriptor file
Please rephrase the above message as

"Requested schema is not found in local repository, please ensure that there are no typos in the XML namespace declaration."

2017-11-08 03:48 UTC, yaminikb commented on appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/node/SaxParserHandler.java
> +                        throw new SAXException(localStrings.getLocalString("invalid.schema", "Requested schema not in local repository, check for typos in the descriptor file"));
Fix the message as mentioned in previous comment.

2017-11-09 05:34 UTC, mskdeepak-oracle commented
@glassfishrobot Run CI tests please

2017-11-09 06:53 UTC, mskdeepak-oracle commented
@glassfishrobot Run CI tests please

2017-11-09 10:31 UTC, mskdeepak-oracle commented
@glassfishrobot Run CI tests please

2017-11-09 12:10 UTC, yaminikb approved these changes

2017-11-09 12:10 UTC, merged