Remove unused Selenium jars
javaee/glassfish pull request #22560
Opened 2018-07-25 12:29 UTC by jayasheelankumar

Remove unused Selenium jars

2018-07-25 12:30 UTC, jayasheelankumar commented
@glassfishrobot run ci tests please

2018-07-26 07:32 UTC, yaminikb requested changes
There are unwanted changes i.e woodstock update. Please fix.

2018-07-26 08:51 UTC, jayasheelankumar commented
@glassfishrobot run ci tests please

2018-07-26 12:46 UTC, yaminikb approved these changes

2018-07-26 12:46 UTC, merged